# Generated by Django 3.1.1 on 2020-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=15)),
                ('Last_Name', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('Mobile', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=15)),
            ],
        ),
    ]
