# Generated by Django 3.1.1 on 2020-09-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_Name', models.CharField(max_length=25)),
                ('Train_Type', models.CharField(max_length=25)),
                ('Source', models.CharField(max_length=20)),
                ('Destination', models.CharField(max_length=20)),
                ('Travel_Time', models.CharField(max_length=15)),
                ('General_Class', models.CharField(max_length=15)),
                ('First_Class', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
